name: Generate Snake Animation

on:
  schedule:
    - cron: '0 */12 * * *' # Every 12 hours
  workflow_dispatch:

jobs:
  build:
    name: Generate and Push Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Generate Snake SVG
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: SUGURU-Get0U
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push SVG to the `output` branch
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
